### ISSUE TITLE
custom loader for package.json

### ISSUE THREAD

**Issue by marcusbesjes** [vigour-io/vpack#11]
This is stemming from an important feature we want from `vigour-package`:

https://github.com/vigour-io/package/issues/1

I think the best approach is to have a custom loader for `package.json` and use `vigour-package` code to provide the correct (parsed) package to the client.

**Comment by DanilloCorvalan** [comment]
low priority. We need to find a way to make the loader load package json from the context (where vpack is being run) and this requires more effort. The main problem is end-projects like ADM that requires Play, which in case requires a plugin. The loader would have to be able to get the file all the way back to ADM. Which makes it a lot complicated.
