### ISSUE TITLE
[Template] Default template including viewport settings

### ISSUE THREAD

**Issue by youzi** [vigour-io/vpack#14]
**Include viewport settings, without creating a custom template.html**

This will enable us to quickly start working on projects without creating a template.html with the correct vp settings (which we always need, since we develop for mobile)

**Comment by DanilloCorvalan** [comment]
@youzi the title of the html page will have to be configured somewhere, maybe on package.json ?

**Comment by youzi** [comment]
@DanilloCorvalan Since this default template is only for dev'ving I think grabbing the package.name would do nicely.

**Comment by DanilloCorvalan** [comment]
@youzi we do also use the template for building and deploying, if I'm not mistaken :)
perhaps use the `description` property of package ?

**Comment by DanilloCorvalan** [comment]
#18
