### ISSUE TITLE
Sourcemap issue

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/vpack#15]
node v4.3.2
npm 3.8.0

throws
```
b/node_modules/vpack/node_modules/url/url.js" is not in the SourceMap.
```
this is not an issue when running without babel

**Comment by jimdebeer** [comment]
probably need to add url to the loader -- @marcusbesjes can you check if this is an issue in url?

**Comment by DanilloCorvalan** [comment]
@jimdebeer @marcusbesjes have you faced this problem with the latest version of vpack? vpack@1.1.18

**Comment by DanilloCorvalan** [comment]
we can open it again if someone be able to reproduce that
