### ISSUE TITLE
default ports

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/vpack#2]
use a characteristic like file path to generate port persistent port numbers for vpack without -port

(use something like crc32)

**Comment by jimdebeer** [comment]
also lets print out the port a bit larger

**Comment by DanilloCorvalan** [comment]
@jimdebeer it already retrieves an available port if you don't specify one through `-p` or `--port`.

**Comment by jimdebeer** [comment]
its not about the available port, its about assigning the same port to the same project based on --- xxx ---  (without port) not very important but just a tad nicer especially when combined with #3

**Comment by jimdebeer** [comment]
you can also use `vigour-util/hash`  but you need to coerce the string to a number

**Comment by DanilloCorvalan** [comment]
@jimdebeer that looks nice! thanks for the explanation :smiley:
