### ISSUE TITLE
Optimizing production builds

### ISSUE THREAD

**Issue by shawninder** [vigour-io/vpack#25]
@ricksmitvigour found some useful insight about how to do this with webpack: http://sokra.github.io/slides/frontend-optimize

see https://github.com/vigour-io/tooling/issues/6

**Comment by ricksmitvigour** [comment]
@shawninder I think it would especially useful for server side rendering and stuff, here's a contained example of server side rendering with webpack. The example uses react but I think it mainly about using webpack for server side rendering

**Comment by shawninder** [comment]
nice man, I'll look into it when we get there (we're currently focusing on Nightmare testing but making vpack the best build tool in existence is our next priority)

**Comment by ricksmitvigour** [comment]
sounds good @shawninder, and having a good testing setup is more important atm. would be like to hear more about testing with nightmare when you have some time.

**Comment by shawninder** [comment]
yeah we're still investigating options, but we will definitely tell everyone when we find some good way to do things
