### ISSUE TITLE
[branch-config] Package settings based on branch

### ISSUE THREAD

**Issue by youzi** [vigour-io/vpack#31]
Like we used to have with https://www.npmjs.com/package/package-branch-config. This enables us to write packages like this:
```json
"develop": {
  "settingForThing": 1
},
"master": {
  "settingForThing": 2
}
```
This enables us to use the same package across different branches. Which enables use to merge smoothly from develop to staging to production.

**Update**
I would suggest the following syntaxes actually, both:
```js
"settingForThing": 0 // default setting
"#develop": {
  "settingForThing": 1 // overwrite on develop
},
"#master": {
  "settingForThing": 2 // overwrite on master
}
//This comes in handy for major differences. eg. player settings.
```
and
```js
"settingForThing": {
  "val": 0, // default setting (not sure about the key, but is consistent with base etc)
  "#develop": 1, // overwrite on develop
  "#master": 2 // overwrite on master
}
//This comes in handy for minor differences. eg. native settings.
```
notes:
- Use `#` because it stands for branch
- Use `#develop` when on feature branch
- Use `#production` when on hotfix branch

/cc @jimdebeer @vigour-io/front-end

**Comment by jimdebeer** [comment]
like the #branch syntax lets go -- we already know that this is a good idea

**Comment by shawninder** [comment]
Totally agree. vpack is next on the tooling list, right after testing

**Comment by youzi** [comment]
This might actually be an issue for the package repo
