### ISSUE TITLE
[dist] Include the dist functionality

### ISSUE THREAD

**Issue by youzi** [vigour-io/vpack#32]
Currently our projects include a `bin/dist`. We need to modularise this and I believe it should be included in our dev/build-tool.

/cc @jimdebeer

**Comment by shawninder** [comment]
We're going to have to plan this out with @marcusbesjes to make sure it integrates well with his js-to-servable-assets vision (see https://github.com/vigour-io/processes-and-culture/commit/0450d123f26bcb2179835838940a40ba38f8dfde#commitcomment-16893464)

**Comment by jimdebeer** [comment]
so we call our builder vigour-pack? or something? does it use browserify? do we need to set it up ourselves? -- very good to separate it from everything else we do  though

**Comment by marcusbesjes** [comment]
Think it makes sense to have a general tool (vpack / vigour-pack) that will do all kinds of tasks for you using other tools (webpack / browserify, wrapper) with logical defaults, then reading your projects package.json, then your command line arguments. Disting should be a part of this, so the `bin/dist` script could be a plugin for vpack to do the `vpack dist` job.
