### ISSUE TITLE
vpack throws a "SourceMap" error when Gaston is not installed

### ISSUE THREAD

**Issue by nfrade** [vigour-io/vpack#33]
On a clean install if you only have vpack installed globally and try to `npm run dev` for example in the vigour-io/player repo, you get a "SourceMap not found" error.
`npm run dev-fast` worked fine but without Babel transpiling.

Tried several install methods and combinations with the same result, but after trying this guide: https://docs.npmjs.com/getting-started/fixing-npm-permissions, and installed Gaston globally it started working.

Installing gaston seems to fix it. Let me know if you can't reproduce it.

**Comment by jimdebeer** [comment]
this is the same error i addressed earlier in https://github.com/vigour-io/vpack/issues/15

**Comment by DanilloCorvalan** [comment]
@nfrade can you confirm your vpack version + node version + npm version + tha'ts it :)
`vpack -v` for version. If it doesn't show up then your vpack is out of date. `npm install -g vpack@latest`

**Comment by nfrade** [comment]
`info vpack 1.1.21`

But I'm using a globally linked vpack to branch [feature/postcss](https://github.com/vigour-io/vpack/tree/feature/postcss). That one has the [hardcoded postcss plugin](https://github.com/vigour-io/vpack/blob/feature/postcss/lib/webpack-config/generate/index.js#L33-L53) and [module](https://github.com/vigour-io/vpack/blob/feature/postcss/lib/webpack-config/generate/module.js#L21-L27) stuff.

**Comment by nfrade** [comment]
Oh but anyway this was before I added the hardcoded stuff.
