### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/vpack#6]
we need to be able to use this tool to build

**Comment by marcusbesjes** [comment]
want
`vpack build --output ./build/base`
to generate
`./build/base/index.html`
`./build/base/build.js`
`./build/base/build.css`

**Comment by DanilloCorvalan** [comment]
`vpack build ./path/to/entry [--output ./path/to/output, --package, --production, --template ./path/to/template.html, --hashes]`
