### ISSUE TITLE
weird mem error (can be web-pack iself)

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/vpack#9]
![image](https://cloud.githubusercontent.com/assets/5682524/13378995/7a046790-de19-11e5-9488-cba04840eddc.png)

**Comment by jimdebeer** [comment]
as you can see it uses 1.4 gb of mem that seems rather execsive

**Comment by DanilloCorvalan** [comment]
@jimdebeer dev-server serves bundled files in memory and all other files too. Maybe you have too many instances running ? I can check later if it's possible to serve it using IO, but then we loose performance on the builds (slower builds)

**Comment by jimdebeer** [comment]
no serve via mem but you have to clean your mem else it becomes a mess (leaking)

**Comment by DanilloCorvalan** [comment]
this is a problem related to webpack, I don't think it's worth neither acheivable implementing something on vpack end. Maybe open an issue at webpack repo or pull request. Closing it.
